/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ApiRegistrationsRouteImport } from './routes/api/registrations'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiCmsRouteImport } from './routes/api/cms'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin-login'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsRoute = ApiRegistrationsRouteImport.update({
  id: '/api/registrations',
  path: '/api/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsRoute = ApiCmsRouteImport.update({
  id: '/api/cms',
  path: '/api/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin-login',
  path: '/api/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cms': typeof ApiCmsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cms': typeof ApiCmsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/admin-login': typeof ApiAdminLoginRoute
  '/api/cms': typeof ApiCmsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/registrations': typeof ApiRegistrationsRoute
  '/products/$productId': typeof ProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/admin-login'
    | '/api/cms'
    | '/api/contact'
    | '/api/registrations'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/admin-login'
    | '/api/cms'
    | '/api/contact'
    | '/api/registrations'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/admin-login'
    | '/api/cms'
    | '/api/contact'
    | '/api/registrations'
    | '/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiCmsRoute: typeof ApiCmsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiRegistrationsRoute: typeof ApiRegistrationsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations': {
      id: '/api/registrations'
      path: '/api/registrations'
      fullPath: '/api/registrations'
      preLoaderRoute: typeof ApiRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms': {
      id: '/api/cms'
      path: '/api/cms'
      fullPath: '/api/cms'
      preLoaderRoute: typeof ApiCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-login': {
      id: '/api/admin-login'
      path: '/api/admin-login'
      fullPath: '/api/admin-login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiCmsRoute: ApiCmsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiRegistrationsRoute: ApiRegistrationsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
